### ISSUE TITLE
Code review week 2

### ISSUE THREAD

**Issue by RobinFrugte97** [Jelmerovereem/web-app-from-scratch-2021#3]
Hey Jelmer!

Coole kaart! Werkt lekker! Ik zie dat je detailpagina's route die je nog uit moet werken. Lekker bezig!

Kijk of je actor diagram wat overzichtelijker kan maken. [Jordy](https://github.com/joordy/web-app-from-scratch-2021#-actor-diagram) heeft een goed voorbeeld, kijk of je er wat uit kan halen. Zorg ervoor dat je diagrams ook precies overeenkomen met je code. In je diagram staat bijvoorbeeld 'main.js', terwijl het in je script 'script.js' heet. Nette flow chart wel!

Misschien kun je je repo een beetje opschonen door de dingen uit de originele fork te verwijderen, zoals examples, docs en course. Dit schept wat meer ruimte en orde.

Goeie Readme, misschien kun je laten zien wat voor data je gebruikt door een snippet van je json te laten zien. Voor de rest netjes. Ik mis wel een beeld van je site in je readme, voeg een goeie screenshot toe! (kan ook als het af is)

Structuur van je code is netjes (flinke tabjes heb je ;)), alles is overzichtelijk. 

Goeie modules! Kijk of je hier nog wat verder in kan gaan, bijvoorbeeld je routing in een aparte modules ipv in je script.js.

Let er op dat je niet te veel in je global-scope zet. Je zou een functie kunnen maken die al je eventlisteners initieert.

Voor de rest goed bezig! Leuke uitwerking ook, ga lekker zo door!

**Comment by Jelmerovereem** [comment]
fab8ec4ef22a7a732f501b617e179c5e95324c02 71fad92a0f5ef7ed2cce4b8ca7eeb002ca6f62e2 abc3c6f19a68c9c78b3681aac579178997cb6015 654c7d8c44517358b45df5896e5054f1141cb223
